default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>

development:
  <<: *default
  database: VoidTV_development

test:
  <<: *default
  database: VoidTV_test

production:
  <<: *default
  database: VoidTV_production
  username: VoidTV
  password: <%= ENV['VOIDTV_DATABASE_PASSWORD'] %>
