# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5984258425d5514549362f04bd8d5250318c38d78d703136f44ac1880b3b1325852f4ad89e90aa5e42b7a301b373f28326add1ae765d809879e131faf7ceec43

test:
  secret_key_base: e05186bd70f9e6e3bc3634bb3b58562d6b14b298f42fb331b236a315c007eb9ef83aeba15b01f04182e43aa48b81d0fa28ce5e483acb4e9cbdcc984060155642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
